spring:
  datasource:
    url: jdbc:mysql://1.94.28.170:3306/food_expiry_reminder?characterEncoding=utf8
    username: root
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl